DROP TABLE IF EXISTS SAMOCHODY;

CREATE TABLE SAMOCHODY(
    id INT AUTO_INCREMENT PRIMARY KEY,
    marka VARCHAR(250) NOT NULL,
    model VARCHAR(250) NOT NULL
);


DROP TABLE IF EXISTS USTERKI;

CREATE TABLE USTERKI(
    id_samochodu INT AUTO_INCREMENT PRIMARY KEY,
    opis VARCHAR(250) NOT NULL
);